/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Calendar;

class AyanaamshaTest {
	@Test void toDegrees() throws Exception {

	Calendar date = Calendar.getInstance();
	date.set(2009, 6, 15); // for 15 July 2009

	double ayanamsha = Ayanaamsha.ayanamsha(date);

	// 23.9853731 in pdf
	assertEquals(23.992896251386888, ayanamsha);
	assertArrayEquals(new int[]{ 23, 59, 34 }, DegMinSec.getGeoCoordsFromDegree(ayanamsha));

	int swissEphermesisMoon[] = { 17, 41, 00 };
	int swissEphermesisSun[] = { 22, 39, 28 };
	int surRaashi = 4; // Karkaataka
	int chaRaashi = 1; // Mesha

	int chandraAbs[] = swissEphermesisMoon;
	chandraAbs[0] = DegMinSec.absGeo(chaRaashi, swissEphermesisMoon);

	int sooryaAbs[] = swissEphermesisSun;
	sooryaAbs[0] = DegMinSec.absGeo(surRaashi, swissEphermesisSun);
	int surNir[] = DegMinSec.getGeoCoordsFromDegree(Ayanaamsha.nirayaana(ayanamsha, sooryaAbs));
	// System.out.printf("Soorya niraayana on %s from Swiss is %s\n", date.getTime(), Arrays.toString(surNir));	

	assertArrayEquals(new int[]{ 88, 39, 54 }, surNir);
	int[] chaNir = DegMinSec.getGeoCoordsFromDegree(Ayanaamsha.nirayaana(ayanamsha, chandraAbs));
	assertArrayEquals(new int[]{ 353, 41, 26 }, chaNir);

	}
}
