/*
 * This source file was generated by the Gradle 'init' task
 */
package org.jyothishaastra;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;

class DegMinSecTest {
    @Test void toDegrees() {
		int ar1[] = { 377, 41, 0 };
		double res = DegMinSec.toDegrees(ar1);
		assertEquals(377.68333333333334, res);

		int ar2[] = { 265, 1, 32 };
		int resAct[] = DegMinSec.add(ar1, ar2); 

		int resExp[] = { 282, 42, 32 };
		assertArrayEquals(resExp, resAct);

		resExp = new int[]{ 112, 39, 28 };
		resAct = DegMinSec.minus(ar1, ar2); 
		assertArrayEquals(resExp, resAct);
    }
}
