/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
		var per = new Person("sf", "la");
        System.out.println(new App().getGreeting());
    }
}

class Somei extends App{

	public String some;
	public Some so;

    String tring() {
		throw new Exception();
        // return "Some []";
    }

}
